package com.bbtutorials.users.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Exercises")
public class ExerciseWeight {
    private String id;
    private String userEmail;
    private String name;
    private Integer lbs;
    private Integer sets;
    private Integer reps;
    private String workoutType;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute(attributeName = "UserEmail")
    public String getUserEmail() { return userEmail; }
    public void setUserEmail(String userEmail) { this.userEmail = userEmail; }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    @DynamoDBAttribute(attributeName = "Lbs")
    public Integer getLbs() { return lbs; }
    public void setLbs(Integer lbs) { this.lbs = lbs; }

    @DynamoDBAttribute(attributeName = "Sets")
    public Integer getSets() { return sets; }
    public void setSets(Integer sets) { this.sets = sets; }

    @DynamoDBAttribute(attributeName = "Reps")
    public Integer getReps() { return reps; }
    public void setReps(Integer reps) { this.reps = reps; }

    @DynamoDBAttribute(attributeName = "WorkoutType")
    public String getWorkoutType() { return workoutType; }
    public void setWorkoutType(String workoutType) { this.workoutType = workoutType; }
}
