package com.bbtutorials.users.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.util.Set;

/**
 * The class used as the model for workouts in DynamoDB.
 * The id attribute serves as the primary key for indexing
 * the database table and is autogenerated whenever a new
 * item is saved to the table.
 *
 * The userEmail attribute is the email of the current user.
 * The daysOfWeek attribute is the integer set corresponding
 * to the specific days of the week, where 0 is Sunday, 1 is
 * Monday, etc. When there are no days of the week for a workout,
 * the set contains a singular -1.
 * The exercises attribute is the set of exercise IDs making up the
 * workout.
 *
 * @author Mark Farber
 */
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Workouts")
public class Workout {
    private String id;
    private String userEmail;
    private String name;
    private Set<String> exercises;
    private Set<Integer> daysOfWeek;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute(attributeName = "UserEmail")
    public String getUserEmail() { return userEmail; }
    public void setUserEmail(String userEmail) { this.userEmail = userEmail; }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    @DynamoDBAttribute(attributeName = "Exercises")
    public Set<String> getExercises() { return exercises; }
    public void setExercises(Set<String> exercises) { this.exercises = exercises; }

    @DynamoDBAttribute(attributeName = "DaysOfWeek")
    public Set<Integer> getDaysOfWeek() { return daysOfWeek; }
    public void setDaysOfWeek(Set<Integer> daysOfWeek) { this.daysOfWeek = daysOfWeek; }
}
